# Basic set up for three package managers
# Documentation -
#   https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "dev"
    labels:
      - "github-actions dependencies"
    commit-message:
      prefix: "gh-actions dev"
      include: "scope"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "dev"
    labels:
      - "npm dependencies"
    commit-message:
      prefix: "npm dev"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "master"
    labels:
      - "github-actions dependencies"
    commit-message:
      prefix: "gh-actions prod"
      include: "scope"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "master"
    labels:
      - "npm dependencies"
    commit-message:
      prefix: "npm prod"
      include: "scope"
