export const mockCollectionsResponse = {
  data: [
    { id: 1 },
    { id: 2 },
    { id: 3 },
    { id: 4 },
    { id: 5 },
    { id: 6 },
    { id: 7 },
    { id: 8 },
    { id: 9 },
    { id: 10 },
    { id: 11 },
    { id: 12 },
  ],
  pagination: {
    total: 3972,
    limit: 12,
    offset: 48,
    total_pages: 331,
    current_page: 5,
  },
};

export const mockArtworkResponse = {
  data: [
    {
      id: 1,
      title: 'Artwork 1',
      image_id: 'img1',
      artist_title: 'Artist 1',
      thumbnail: 'thumb1',
      artist_id: 'aid1',
    },
    {
      id: 2,
      title: 'Artwork 2',
      image_id: 'img2',
      artist_title: 'Artist 2',
      thumbnail: 'thumb2',
      artist_id: 'aid2',
    },
    {
      id: 3,
      title: 'Artwork 3',
      image_id: 'img3',
      artist_title: 'Artist 3',
      thumbnail: 'thumb3',
      artist_id: 'aid3',
    },
    {
      id: 4,
      title: 'Artwork 4',
      image_id: 'img4',
      artist_title: 'Artist 4',
      thumbnail: 'thumb4',
      artist_id: 'aid4',
    },
    {
      id: 5,
      title: 'Artwork 5',
      image_id: 'img5',
      artist_title: 'Artist 5',
      thumbnail: 'thumb5',
      artist_id: 'aid5',
    },
    {
      id: 6,
      title: 'Artwork 6',
      image_id: 'img6',
      artist_title: 'Artist 6',
      thumbnail: 'thumb6',
      artist_id: 'aid6',
    },
    {
      id: 7,
      title: 'Artwork 7',
      image_id: 'img7',
      artist_title: 'Artist 7',
      thumbnail: 'thumb7',
      artist_id: 'aid7',
    },
    {
      id: 8,
      title: 'Artwork 8',
      image_id: 'img8',
      artist_title: 'Artist 8',
      thumbnail: 'thumb8',
      artist_id: 'aid8',
    },
    {
      id: 9,
      title: 'Artwork 9',
      image_id: 'img9',
      artist_title: 'Artist 9',
      thumbnail: 'thumb9',
      artist_id: 'aid9',
    },
    {
      id: 10,
      title: 'Artwork 10',
      image_id: 'img10',
      artist_title: 'Artist 10',
      thumbnail: 'thumb10',
      artist_id: 'aid10',
    },
    {
      id: 11,
      title: 'Artwork 11',
      image_id: 'img11',
      artist_title: 'Artist 11',
      thumbnail: 'thumb11',
      artist_id: 'aid11',
    },
    {
      id: 12,
      title: 'Artwork 12',
      image_id: 'img12',
      artist_title: 'Artist 12',
      thumbnail: 'thumb12',
      artist_id: 'aid12',
    },
  ],
};
