name: Dev Environment Deploy Workflow for Kanbook CI

on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build, test, and deploy
        run: |
          npm i
          npm run build
          npm install -g firebase-tools
          firebase deploy -P dev --token ${{ secrets.FIREBASE_TOKEN }}
          TESTENV=cal-portfolio-dev.web.app npm run test:e2e
        env:
          CI: true
          REACT_APP_NODE_ENV: "dev"
          REACT_APP_DEV_API_KEY: ${{ secrets.REACT_APP_DEV_API_KEY }}
          REACT_APP_DEV_AUTH_DOMAIN: ${{ secrets.REACT_APP_DEV_AUTH_DOMAIN }}
          REACT_APP_DEV_DATABASE_URL: ${{ secrets.REACT_APP_DEV_DATABASE_URL }}
          REACT_APP_DEV_PROJECT_ID: ${{ secrets.REACT_APP_DEV_PROJECT_ID }}
          REACT_APP_DEV_STORAGE_BUCKET: ${{ secrets.REACT_APP_DEV_STORAGE_BUCKET }}
          REACT_APP_DEV_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_DEV_MESSAGING_SENDER_ID }}
          REACT_APP_DEV_APP_ID: ${{ secrets.REACT_APP_DEV_APP_ID }}
          REACT_APP_DEV_MEASUREMENT_ID: ${{ secrets.REACT_APP_DEV_MEASUREMENT_ID }}
